language: node_js
node_js:
- 5.11
before_deploy:
- npm run demo
deploy:
  provider: heroku
  api_key:
    secure: o6AcQLLmRhoKlcKviGrXKntVWNsCuDDoq8XxtuK8Pqwhotlk6qsfWOjPFf286qNJYT0VzQ7AiqwdCuuT8xFyPl4RndptLC6XMgq409wPfR5JJWZWC5sr1bx3rHTWn/PbI4vZcPuNmHffebqDRKx4LqJz4ULVJS/VbXe9P65UVU4=
  skip_cleanup: true
